version: 2
updates:
  # Keep GitHub Actions up to date.
  # https://docs.github.com/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci(deps)"
